# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://jamosf.github.io
date_format: "ordinal"
title: 不止
# subtitle: "像疯子一样活着"
description: "Jamosf的个人博客"
keywords: Jamosf
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
# author: Jamos
# organization: ZTE, Inc.
# organization_url: https://www.zte.com
# location: shanghai, China
# email: fengshangren81@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
   -
    href: /mybook
    label: 生活琐碎

  -
   href: /economy
   label: 投资理财

  # -
  #  href: /wiki/
  #  label: 维基

  # -
  #  href: /links/
  #  label: 链接

  # -
  #  href: /about/
  #  label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# repository: fengshangren/fengshangren.github.io

# ---------------- #
#      Socials     #
# ---------------- #
# github_username: fengshangren
# facebook_username: 冯上任
# weibo_username: CSU老马冇敌SJTU
# zhihu_username: 加摩斯
# twitter_username: jacky long

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
#comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
#duoshuo_username: mazhuang
#disqus_username: mzlogin
# 在使用 disqus 的时候可点击显示多说评论框
#lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Python]
skill_mobile_app_keywords: [Android]
skill_windows_keywords: [BCB, VC++, MFC]
